<?php
/** @var \Expertime\ImportCustom\Block\Customer\Account $block */
?>
<!--<div class="field file-upload">-->
<!--            <label for="customer_image" class="label"><span>--><?php //echo __('Avatar') ?><!--</span></label>-->
<!--            <div class="control">-->
<!--                <input type="file" name="customer_image" id="customer_image" title="--><?php //echo __('Custom Image') ?><!--" class="input-text" data-validate="{required:false}">-->
<!--            </div>-->
<!--</div>-->

<div class="field file-upload">
    <label for="customer_image" class="label"><span><?php echo __('Avatar') ?></span></label>
    <div class="control">
        <input type="text" name="customer_image" value="" title="<?php echo __('Custom Image') ?>" class="input-text" id="customer_image">
    </div>
</div>