<fieldset class="fieldset create account" data-hasrequired="<?php echo __('* Required Fields') ?>">
        <legend class="legend">
                <span><?php echo __('Image Uploaded') ?></span>
         </legend>

        <?php if ($url = $block->getFileUrl()): ?>
            <div class="field">
                    <img src="<?php echo $url ?>" alt="image" />
             </div>
        <?php endif; ?>
</fieldset>